apiVersion: v1
kind: Service
metadata:
  name: {{ include "sctp.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "sctp.name" . }}
    helm.sh/chart: {{ include "sctp.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodeport }}
      targetPort: sctp
      protocol: SCTP
      name: sctp
  selector:
    app.kubernetes.io/name: {{ include "sctp.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
